//
// Created by Mariangela Evangelista on 15/05/18.
//

#ifndef PROVA_PARAMETERS_H
#define PROVA_PARAMETERS_H

#include "dataset.h"


#define DRIVE_EXTENSION ".tif"
#define DRIVE_SE_SIZE_MASK_EROSION 11
#define DRIVE_SE_SIZE_RECONSTRUCTION_EROSION 5
#define DRIVE_SE_LENGHT_SUMTOPHAT 9
#define DRIVE_SE_HEIGHT_SUMTOPHAT 11
#define DRIVE_ANGLES_SUMTOPHAT 20
#define DRIVE_DENOISING_2 20
#define DRIVE_AREA 80
#define DRIVE_CIRCULARITY 0.8
#define DRIVE_AREA_HOLE_FILLING 100


#define CHASEDB1_IMAGES_EXTENSION ".jpg"
#define CHASEDB1_MASKS_EXTENSION ".png"
#define CHASEDB1_TRUTHS_EXTENSION ".png"
#define CHASEDB1_SE_SIZE_MASK_EROSION 22
#define CHASEDB1_SE_SIZE_RECONSTRUCTION_EROSION 15
#define CHASEDB1_SE_LENGHT_SUMTOPHAT 17
#define CHASEDB1_SE_HEIGHT_SUMTOPHAT 17
#define CHASEDB1_ANGLES_SUMTOPHAT 6
#define CHASEDB1_DENOISING_2 10
#define CHASEDB1_AREA 100
#define CHASEDB1_CIRCULARITY 0.5
#define CHASEDB1_AREA_HOLE_FILLING 200


#define STARE_EXTENSION ".ppm"
#define STARE_MASKS_EXTENSION ".tif"
#define STARE_TRUTHS_EXTENSION ".ppm"
#define STARE_SE_SIZE_MASK_EROSION 15
#define STARE_SE_SIZE_RECONSTRUCTION_EROSION 5
#define STARE_SE_LENGHT_SUMTOPHAT 11
#define STARE_SE_HEIGHT_SUMTOPHAT 13
#define STARE_ANGLES_SUMTOPHAT 10
#define STARE_DENOISING_2 7
#define STARE_AREA 100
#define STARE_CIRCULARITY 0.5
#define STARE_AREA_HOLE_FILLING 100

#endif //PROVA_PARAMETERS_H
